import type { DayMoment } from './timeOfDay';

/** Explicit time-of-day for every task across the nine plan-eligible programs, keyed by the
 * exact English task string. The heuristic classifier in timeOfDay.ts is a reasonable guess for
 * text it's never seen, but it still leaves plenty of genuinely flexible-sounding tasks (an
 * exercise set, a step count) in the vague "anytime" bucket. This map pins every one of them to
 * a specific, deliberate moment instead, so nothing in the merged plan is ever left undated. */
export const TASK_MOMENT_OVERRIDE: Record<string, DayMoment> = {
  // face-structure
  'Full-tongue mewing, 3× 10-min holds': 'morning',
  'Nose-breathing check every waking hour': 'twice_daily',
  'Cheekbone lift: 3 sets of 15': 'afternoon',
  'Morning + evening face massage, 2 min': 'twice_daily',
  'Continuous mewing all day': 'twice_daily',
  'Cheekbone lift: 4 sets of 15': 'afternoon',
  'Cheek hollow holds: 3 × 10s': 'afternoon',
  'Face massage along cheek + jaw, 3 min': 'evening',
  'Mewing + hard swallow reps, 3 sets': 'morning',
  'Cheek circuit: 4 rounds': 'afternoon',
  'Under-eye tapping massage, 2 min': 'morning',
  'Cold-water face rinse, 30s': 'morning',
  'Effortless all-day mewing (habit check)': 'twice_daily',
  'Full face circuit: 5 rounds': 'afternoon',
  'Progress photo, front + profile': 'morning',
  'Massage + cold-rinse recovery': 'evening',

  // jawmaxing
  'Warm-up: 20 slow jaw clenches': 'morning',
  'Resistance gum: 3 min per side': 'afternoon',
  'Chin tucks: 3 sets of 12': 'afternoon',
  'Jaw massage, 2 min': 'evening',
  'Firm gum: 5 min per side': 'afternoon',
  'Static clench holds: 3 × 20s': 'afternoon',
  'Chin tucks: 4 sets of 15': 'afternoon',
  'Neck + jaw stretch, 2 min': 'evening',
  'Hard gum: 6 min per side': 'afternoon',
  'Weighted clench holds: 4 × 20s': 'afternoon',
  'Lower-lip pull downs: 3 sets of 15': 'afternoon',
  'Deep jaw massage, 3 min': 'evening',
  'Gum circuit: 5 min per side': 'afternoon',
  'Clench pyramid: 5 descending sets': 'afternoon',
  'Progress photo, profile + 45°': 'morning',
  'Full jaw + neck recovery massage': 'evening',

  // hunter-eyes
  'Side-gaze holds: 3 × 8s per side': 'morning',
  'Under-eye de-puff cold compress, 60s': 'morning',
  'Outer-corner lift + squint: 3 × 12': 'afternoon',
  'Inner-to-outer eye massage, 90s': 'morning',
  'Outer-corner lift resistance: 4 × 12 per side': 'morning',
  'Squint holds: 3 × 10s': 'afternoon',
  'Brow-set downward press: 3 × 15': 'afternoon',
  'Cold compress + massage, 2 min': 'morning',
  'Outer-corner + brow combo: 4 rounds': 'morning',
  'Sustained squint holds: 4 × 12s': 'afternoon',
  'Temple + eye-area massage, 2 min': 'evening',
  'Screen-distance + sleep habit check': 'evening',
  'Full eye-area circuit: 5 rounds': 'morning',
  'De-puff + massage, morning and evening': 'twice_daily',
  'Progress photo, neutral gaze': 'morning',
  'Recovery: compress + massage': 'evening',

  // posture
  'Chest doorway stretch: 3 × 30s': 'afternoon',
  'Upper-back stretch over a chair: 10 reps': 'afternoon',
  'Hourly posture reset alarm': 'twice_daily',
  'Wall angels: 3 sets of 12': 'morning',
  'Band pull-aparts: 3 sets of 20': 'afternoon',
  'Chin tucks: 4 sets of 12': 'afternoon',
  'Desk setup check': 'morning',
  'Face pulls: 4 sets of 15': 'afternoon',
  'Wall angels + Y-T-W raises': 'afternoon',
  'Gentle neck-strengthening holds: 3 × 20s': 'morning',
  'Standing posture holds through the day': 'twice_daily',
  'Full posture circuit': 'afternoon',
  'Loaded carries: 3 sets': 'afternoon',
  'Progress photo, side profile': 'morning',
  'All-day alignment habit check': 'twice_daily',

  // bodymaxing
  'Push session: chest, shoulders, triceps': 'afternoon',
  'Lateral raises: 4 sets of 15': 'afternoon',
  '8k steps for the day': 'afternoon',
  'Eat enough protein through the day': 'afternoon',
  'Pull session: back, rear delts, biceps': 'afternoon',
  'Lateral raises: 5 sets of 15': 'afternoon',
  '10k steps for the day': 'afternoon',
  'Protein target + eat a little lighter': 'afternoon',
  'Push + pull combo circuit': 'afternoon',
  'Overhead press: 4 heavy sets': 'afternoon',
  'Core hold: 3 × 20s': 'morning',
  '10k steps + protein target': 'afternoon',
  'Full-body strength circuit': 'afternoon',
  'Shoulder finisher: 6 sets': 'afternoon',
  'Progress photo, front + back': 'morning',
  'Eat a little lighter + protein + 10k steps': 'afternoon',

  // sleep
  'Fixed wake time, 7 days': 'wake_up',
  'Morning sunlight within 30 min': 'morning',
  'No caffeine after 2pm': 'afternoon',
  'Screens off 60 min before bed': 'before_bed',
  'Cool, dark room (18°C)': 'before_bed',
  'Wind-down routine, 30 min': 'before_bed',
  'No large meals 3h before bed': 'evening',
  'Consistent bedtime ±15 min': 'before_bed',
  'Magnesium + no alcohol test': 'before_bed',
  'Blue-light filter after sunset': 'evening',
  'Breathing / relaxation, 5 min': 'before_bed',
  'Track sleep + morning puffiness': 'morning',
  'Full routine nightly': 'evening',
  'Consistent 8h achieved': 'morning',
  'Review de-puff in AM photos': 'morning',
  'Set permanent sleep schedule': 'before_bed',

  // hydration
  'Water: 500ml on waking': 'wake_up',
  'Reach 2.5L across the day': 'afternoon',
  'A pinch of natural salt in your water once a day': 'morning',
  'Cut excess salt + alcohol': 'evening',
  '3L water target': 'afternoon',
  'Potassium-rich foods (bananas, greens) in meals': 'afternoon',
  'Herbal tea instead of late caffeine': 'evening',
  'Track AM facial puffiness': 'morning',
  'Front-load water before evening': 'morning',
  'Natural minerals in the morning + after training': 'morning',
  'Water-rich foods each meal': 'afternoon',
  'Cold-water face rinse AM': 'morning',
  'Consistent 3L habit': 'afternoon',
  'De-puff routine locked': 'morning',
  'Progress photo, AM face': 'morning',
  'Review energy + skin clarity': 'evening',

  // skinmaxing (natural)
  'Cool water rinse + pure aloe vera gel, on waking': 'wake_up',
  'Raw honey mask, 10 min before bed': 'before_bed',
  'Water target: 2.5L across the day': 'afternoon',
  'Pillowcase change (2×/week)': 'evening',
  'Jojoba oil, a few drops as an evening treatment': 'evening',
  'Rose water mist, morning': 'morning',
  'Sleep 7.5h+': 'before_bed',
  'No touching / picking (habit check)': 'twice_daily',
  'Oat + yogurt mask, once a week': 'evening',
  'Protein + vitamin-C rich meals': 'afternoon',
  'Facial massage with a natural oil, 3 min': 'evening',
  'Reapply natural sun protection': 'afternoon',
  'Full morning + evening ritual': 'twice_daily',
  'Gentle honey-sugar scrub, once a week': 'evening',
  'Sleep + hydration + sun-care streak': 'evening',

  // skin-clarity (natural)
  'Gentle water rinse, morning and evening': 'twice_daily',
  'Green tea compress on active spots, evening': 'evening',
  'Natural sun protection every morning': 'morning',
  'Cut dairy + high-sugar test': 'afternoon',
  'Chamomile steam, 5 min, twice a week — evening': 'evening',
  'Light, natural moisturizer': 'morning',
  'Clean phone screen + pillowcase': 'evening',
  'Hydrate 2.5L + sleep 7.5h': 'afternoon',
  'Green clay mask, once a week — evening': 'evening',
  'Continue compresses + spot care': 'evening',
  'Reapply sun protection midday': 'afternoon',
  'No picking (streak check)': 'twice_daily',
  'Maintenance ritual locked': 'twice_daily',
  'Weekly clay mask': 'evening',
  'Progress photo, bare skin': 'morning',
  'Diet + sleep + hydration review': 'afternoon',
};

/** Resolves a task's moment from the curated override first — falling back to the heuristic
 * classifier only for text this map has never seen (e.g. a task added later that wasn't
 * re-curated yet). */
export function resolveTaskMoment(enTask: string, fallback: (task: string) => DayMoment): DayMoment {
  return TASK_MOMENT_OVERRIDE[enTask] ?? fallback(enTask);
}
